

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "nimlotherion"
version = "0.1.0"
dependencies = [
    "chardet>=5.2.0",
    "concurrent-log-handler>=0.9.25",
    "cryptography>=42.0.5",
    "PyYaml>=6.0.1",
    "SQLAlchemy>=2.0.29",
    "toml>=0.10.2"
]
requires-python = ">=3.12"
authors = [
  { name = "Alan Wamberger", email = "awamberger@proton.me" },
]
maintainers = [
  {name = "Alan Wamberger", email = "awamberger@proton.me"}
]
description = "Lightweight Microframework for data transfer/integrations"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["nimlotherion", "db"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development"
]


[project.urls]
Homepage = ""
Documentation = ""
Repository = ""
Issues = ""
Changelog = ""


[project.scripts]
nimlotherion = "nimlotherion.tools.build:build_template"
